# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(592, 436)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 20, 151, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 210, 71, 16))
        self.label_4.setObjectName("label_4")
        self.txtplaintext = QtWidgets.QTextEdit(self.centralwidget)
        self.txtplaintext.setGeometry(QtCore.QRect(160, 50, 341, 71))
        self.txtplaintext.setObjectName("txtplaintext")
        self.txtkey = QtWidgets.QTextEdit(self.centralwidget)
        self.txtkey.setGeometry(QtCore.QRect(160, 140, 341, 41))
        self.txtkey.setObjectName("txtkey")
        self.txtciphertext = QtWidgets.QTextEdit(self.centralwidget)
        self.txtciphertext.setGeometry(QtCore.QRect(160, 200, 341, 71))
        self.txtciphertext.setObjectName("txtciphertext")
        self.encryptbtn = QtWidgets.QPushButton(self.centralwidget)
        self.encryptbtn.setGeometry(QtCore.QRect(160, 310, 75, 23))
        self.encryptbtn.setObjectName("encryptbtn")
        self.decryptbtn = QtWidgets.QPushButton(self.centralwidget)
        self.decryptbtn.setGeometry(QtCore.QRect(410, 310, 75, 23))
        self.decryptbtn.setObjectName("decryptbtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 592, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Caesar Cipher"))
        self.label_2.setText(_translate("MainWindow", "Plain text:"))
        self.label_3.setText(_translate("MainWindow", "Key:"))
        self.label_4.setText(_translate("MainWindow", "Cipher text:"))
        self.encryptbtn.setText(_translate("MainWindow", "Encrypt"))
        self.decryptbtn.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
