# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 633)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 60, 81, 16))
        self.label.setObjectName("label")
        self.generatekeysBtn = QtWidgets.QPushButton(self.centralwidget)
        self.generatekeysBtn.setGeometry(QtCore.QRect(420, 60, 111, 23))
        self.generatekeysBtn.setObjectName("generatekeysBtn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 160, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 320, 81, 16))
        self.label_3.setObjectName("label_3")
        self.informationTxt = QtWidgets.QTextEdit(self.centralwidget)
        self.informationTxt.setGeometry(QtCore.QRect(220, 140, 531, 71))
        self.informationTxt.setObjectName("informationTxt")
        self.signatureTxt = QtWidgets.QTextEdit(self.centralwidget)
        self.signatureTxt.setGeometry(QtCore.QRect(220, 300, 531, 71))
        self.signatureTxt.setObjectName("signatureTxt")
        self.signBtn = QtWidgets.QPushButton(self.centralwidget)
        self.signBtn.setGeometry(QtCore.QRect(280, 410, 111, 23))
        self.signBtn.setObjectName("signBtn")
        self.verifyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.verifyBtn.setGeometry(QtCore.QRect(580, 410, 111, 23))
        self.verifyBtn.setObjectName("verifyBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ECC Cipher"))
        self.generatekeysBtn.setText(_translate("MainWindow", "Generate keys"))
        self.label_2.setText(_translate("MainWindow", "Information:"))
        self.label_3.setText(_translate("MainWindow", "Signature:"))
        self.signBtn.setText(_translate("MainWindow", "Sign"))
        self.verifyBtn.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
