# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(972, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 20, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 240, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 80, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 220, 71, 16))
        self.label_5.setObjectName("label_5")
        self.generatekeysbtn = QtWidgets.QPushButton(self.centralwidget)
        self.generatekeysbtn.setGeometry(QtCore.QRect(470, 20, 111, 23))
        self.generatekeysbtn.setObjectName("generatekeysbtn")
        self.plaintext = QtWidgets.QTextEdit(self.centralwidget)
        self.plaintext.setGeometry(QtCore.QRect(100, 80, 321, 71))
        self.plaintext.setObjectName("plaintext")
        self.ciphertext = QtWidgets.QTextEdit(self.centralwidget)
        self.ciphertext.setGeometry(QtCore.QRect(100, 210, 321, 71))
        self.ciphertext.setObjectName("ciphertext")
        self.informationtext = QtWidgets.QTextEdit(self.centralwidget)
        self.informationtext.setGeometry(QtCore.QRect(570, 80, 381, 71))
        self.informationtext.setObjectName("informationtext")
        self.signaturetxt = QtWidgets.QTextEdit(self.centralwidget)
        self.signaturetxt.setGeometry(QtCore.QRect(570, 210, 381, 71))
        self.signaturetxt.setObjectName("signaturetxt")
        self.encryptbtn = QtWidgets.QPushButton(self.centralwidget)
        self.encryptbtn.setGeometry(QtCore.QRect(90, 350, 75, 23))
        self.encryptbtn.setObjectName("encryptbtn")
        self.decryptbtn = QtWidgets.QPushButton(self.centralwidget)
        self.decryptbtn.setGeometry(QtCore.QRect(260, 350, 75, 23))
        self.decryptbtn.setObjectName("decryptbtn")
        self.signbtn = QtWidgets.QPushButton(self.centralwidget)
        self.signbtn.setGeometry(QtCore.QRect(620, 350, 75, 23))
        self.signbtn.setObjectName("signbtn")
        self.verifybtn = QtWidgets.QPushButton(self.centralwidget)
        self.verifybtn.setGeometry(QtCore.QRect(800, 350, 75, 23))
        self.verifybtn.setObjectName("verifybtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA Cipher"))
        self.label_2.setText(_translate("MainWindow", "Plain text:"))
        self.label_3.setText(_translate("MainWindow", "Cipher text:"))
        self.label_4.setText(_translate("MainWindow", "Information:"))
        self.label_5.setText(_translate("MainWindow", "Signature:"))
        self.generatekeysbtn.setText(_translate("MainWindow", "Generate Keys"))
        self.encryptbtn.setText(_translate("MainWindow", "Encrypt"))
        self.decryptbtn.setText(_translate("MainWindow", "Decrypt"))
        self.signbtn.setText(_translate("MainWindow", "Sign"))
        self.verifybtn.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
